---
# Install Java 11 (Amazon Corretto â€“ correct for AL2023)
- name: Install Java 11 (Amazon Corretto)
  dnf:
    name:
      - java-11-amazon-corretto
    state: present

# Install Git
- name: Install Git
  dnf:
    name: git
    state: present

# Install Maven
- name: Install Maven
  dnf:
    name: maven
    state: present

# Add Jenkins repository
- name: Add Jenkins repository
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: "0644"

# Import Jenkins GPG key
- name: Import Jenkins GPG key
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    state: present

# Install Jenkins
- name: Install Jenkins
  dnf:
    name: jenkins
    state: present
  notify: Start and Enable Jenkins Service
